import { Entity, EntityPluralNames } from '../constants/Entities';

export const AccountModel = {
	_entityName: Entity.Account,
	_entityPluralName: EntityPluralNames.Account,
	_id: Entity.Account + 'id',

	preferredcontactmethodcodename: 'preferredcontactmethodcodename',
	emailaddress3: 'emailaddress3',
	emailaddress2: 'emailaddress2',
	emailaddress1: 'emailaddress1',
	masteraccountidyominame: 'masteraccountidyominame',
	address1_city: 'address1_city',
	slaid: 'slaid',
	slaidLookup: '_slaid_value',
	address2_freighttermscodename: 'address2_freighttermscodename',
	modifiedon: 'modifiedon',
	aging90: 'aging90',
	overriddencreatedon: 'overriddencreatedon',
	websiteurl: 'websiteurl',
	address1_longitude: 'address1_longitude',
	donotpostalmail: 'donotpostalmail',
	createdbyexternalpartyname: 'createdbyexternalpartyname',
	address1_addresstypecode: 'address1_addresstypecode',
	transactioncurrencyid: 'transactioncurrencyid',
	transactioncurrencyidLookup: '_transactioncurrencyid_value',
	sharesoutstanding: 'sharesoutstanding',
	donotsendmm: 'donotsendmm',
	createdbyexternalparty: 'createdbyexternalparty',
	createdbyexternalpartyLookup: '_createdbyexternalparty_value',
	creditonhold: 'creditonhold',
	transactioncurrencyidname: 'transactioncurrencyidname',
	aging30: 'aging30',
	donotbulkpostalmail: 'donotbulkpostalmail',
	yominame: 'yominame',
	preferredsystemuseridyominame: 'preferredsystemuseridyominame',
	address1_shippingmethodcode: 'address1_shippingmethodcode',
	paymenttermscode: 'paymenttermscode',
	slainvokedid: 'slainvokedid',
	slainvokedidLookup: '_slainvokedid_value',
	modifiedbyexternalpartyyominame: 'modifiedbyexternalpartyyominame',
	businesstypecodename: 'businesstypecodename',
	masteraccountidname: 'masteraccountidname',
	preferredsystemuseridname: 'preferredsystemuseridname',
	accountcategorycode: 'accountcategorycode',
	preferredappointmentdaycodename: 'preferredappointmentdaycodename',
	address2_stateorprovince: 'address2_stateorprovince',
	participatesinworkflowname: 'participatesinworkflowname',
	address2_country: 'address2_country',
	accountcategorycodename: 'accountcategorycodename',
	address2_line2: 'address2_line2',
	aging60_base: 'aging60_base',
	address1_line3: 'address1_line3',
	onholdtime: 'onholdtime',
	address1_freighttermscode: 'address1_freighttermscode',
	creditlimit: 'creditlimit',
	parentaccountidname: 'parentaccountidname',
	accountratingcode: 'accountratingcode',
	address1_utcoffset: 'address1_utcoffset',
	preferredappointmenttimecode: 'preferredappointmenttimecode',
	donotsendmarketingmaterialname: 'donotsendmarketingmaterialname',
	numberofemployees: 'numberofemployees',
	modifiedbyexternalpartyname: 'modifiedbyexternalpartyname',
	statecodename: 'statecodename',
	accountclassificationcode: 'accountclassificationcode',
	revenue: 'revenue',
	customertypecode: 'customertypecode',
	donotbulkpostalmailname: 'donotbulkpostalmailname',
	exchangerate: 'exchangerate',
	address2_county: 'address2_county',
	isprivate: 'isprivate',
	primarycontactid: 'primarycontactid',
	primarycontactidLookup: '_primarycontactid_value',
	telephone3: 'telephone3',
	parentaccountid: 'parentaccountid',
	parentaccountidLookup: '_parentaccountid_value',
	address2_city: 'address2_city',
	statuscode: 'statuscode',
	address1_addresstypecodename: 'address1_addresstypecodename',
	address2_latitude: 'address2_latitude',
	createdon: 'createdon',
	donotbulkemail: 'donotbulkemail',
	donotfax: 'donotfax',
	marketcap: 'marketcap',
	address1_composite: 'address1_composite',
	ownershipcode: 'ownershipcode',
	statuscodename: 'statuscodename',
	owningbusinessunit: 'owningbusinessunit',
	owningbusinessunitLookup: '_owningbusinessunit_value',
	preferredappointmenttimecodename: 'preferredappointmenttimecodename',
	address2_postalcode: 'address2_postalcode',
	lastusedincampaign: 'lastusedincampaign',
	paymenttermscodename: 'paymenttermscodename',
	industrycodename: 'industrycodename',
	processid: 'processid',
	owneridyominame: 'owneridyominame',
	entityimage_url: 'entityimage_url',
	address2_shippingmethodcodename: 'address2_shippingmethodcodename',
	address2_line3: 'address2_line3',
	description: 'description',
	modifiedby: 'modifiedby',
	modifiedbyLookup: '_modifiedby_value',
	timezoneruleversionnumber: 'timezoneruleversionnumber',
	address1_county: 'address1_county',
	createdbyname: 'createdbyname',
	shippingmethodcodename: 'shippingmethodcodename',
	preferredcontactmethodcode: 'preferredcontactmethodcode',
	modifiedonbehalfby: 'modifiedonbehalfby',
	modifiedonbehalfbyLookup: '_modifiedonbehalfby_value',
	address1_line1: 'address1_line1',
	donotemail: 'donotemail',
	territorycode: 'territorycode',
	donotphonename: 'donotphonename',
	address2_postofficebox: 'address2_postofficebox',
	address2_telephone1: 'address2_telephone1',
	address2_telephone2: 'address2_telephone2',
	address2_telephone3: 'address2_telephone3',
	address1_addressid: 'address1_addressid',
	traversedpath: 'traversedpath',
	territorycodename: 'territorycodename',
	followemailname: 'followemailname',
	address1_telephone2: 'address1_telephone2',
	createdonbehalfbyname: 'createdonbehalfbyname',
	owninguser: 'owninguser',
	owninguserLookup: '_owninguser_value',
	industrycode: 'industrycode',
	address2_name: 'address2_name',
	primarysatoriid: 'primarysatoriid',
	name: 'name',
	entityimageid: 'entityimageid',
	aging60: 'aging60',
	timespentbymeonemailandmeetings: 'timespentbymeonemailandmeetings',
	businesstypecode: 'businesstypecode',
	primarytwitterid: 'primarytwitterid',
	owneridname: 'owneridname',
	entityimage: 'entityimage',
	entityimage_timestamp: 'entityimage_timestamp',
	createdonbehalfbyyominame: 'createdonbehalfbyyominame',
	address2_composite: 'address2_composite',
	accountratingcodename: 'accountratingcodename',
	shippingmethodcode: 'shippingmethodcode',
	address1_country: 'address1_country',
	customertypecodename: 'customertypecodename',
	owningteam: 'owningteam',
	owningteamLookup: '_owningteam_value',
	address1_stateorprovince: 'address1_stateorprovince',
	isprivatename: 'isprivatename',
	marketingonly: 'marketingonly',
	creditonholdname: 'creditonholdname',
	modifiedonbehalfbyname: 'modifiedonbehalfbyname',
	createdbyexternalpartyyominame: 'createdbyexternalpartyyominame',
	address1_freighttermscodename: 'address1_freighttermscodename',
	createdonbehalfby: 'createdonbehalfby',
	createdonbehalfbyLookup: '_createdonbehalfby_value',
	marketingonlyname: 'marketingonlyname',
	address2_line1: 'address2_line1',
	address1_telephone1: 'address1_telephone1',
	primarycontactidname: 'primarycontactidname',
	address1_telephone3: 'address1_telephone3',
	address1_postofficebox: 'address1_postofficebox',
	followemail: 'followemail',
	donotemailname: 'donotemailname',
	slainvokedidname: 'slainvokedidname',
	fax: 'fax',
	masterid: 'masterid',
	masteridLookup: '_masterid_value',
	sic: 'sic',
	ownerid: 'ownerid',
	address2_utcoffset: 'address2_utcoffset',
	stageid: 'stageid',
	accountnumber: 'accountnumber',
	creditlimit_base: 'creditlimit_base',
	address2_fax: 'address2_fax',
	revenue_base: 'revenue_base',
	merged: 'merged',
	owneridtype: 'owneridtype',
	address2_longitude: 'address2_longitude',
	modifiedbyexternalparty: 'modifiedbyexternalparty',
	modifiedbyexternalpartyLookup: '_modifiedbyexternalparty_value',
	ftpsiteurl: 'ftpsiteurl',
	donotpostalmailname: 'donotpostalmailname',
	aging90_base: 'aging90_base',
	donotphone: 'donotphone',
	address1_shippingmethodcodename: 'address1_shippingmethodcodename',
	address1_primarycontactname: 'address1_primarycontactname',
	modifiedbyyominame: 'modifiedbyyominame',
	lastonholdtime: 'lastonholdtime',
	address1_line2: 'address1_line2',
	modifiedonbehalfbyyominame: 'modifiedonbehalfbyyominame',
	createdby: 'createdby',
	createdbyLookup: '_createdby_value',
	address2_addresstypecode: 'address2_addresstypecode',
	address2_upszone: 'address2_upszone',
	donotfaxname: 'donotfaxname',
	marketcap_base: 'marketcap_base',
	address2_addresstypecodename: 'address2_addresstypecodename',
	ownershipcodename: 'ownershipcodename',
	address1_postalcode: 'address1_postalcode',
	tickersymbol: 'tickersymbol',
	customersizecode: 'customersizecode',
	utcconversiontimezonecode: 'utcconversiontimezonecode',
	donotbulkemailname: 'donotbulkemailname',
	participatesinworkflow: 'participatesinworkflow',
	stockexchange: 'stockexchange',
	customersizecodename: 'customersizecodename',
	importsequencenumber: 'importsequencenumber',
	telephone2: 'telephone2',
	mergedname: 'mergedname',
	versionnumber: 'versionnumber',
	preferredsystemuserid: 'preferredsystemuserid',
	preferredsystemuseridLookup: '_preferredsystemuserid_value',
	accountid: 'accountid',
	telephone1: 'telephone1',
	aging30_base: 'aging30_base',
	address1_name: 'address1_name',
	address1_fax: 'address1_fax',
	address1_latitude: 'address1_latitude',
	address2_shippingmethodcode: 'address2_shippingmethodcode',
	primarycontactidyominame: 'primarycontactidyominame',
	accountclassificationcodename: 'accountclassificationcodename',
	preferredappointmentdaycode: 'preferredappointmentdaycode',
	modifiedbyname: 'modifiedbyname',
	createdbyyominame: 'createdbyyominame',
	address2_freighttermscode: 'address2_freighttermscode',
	address1_upszone: 'address1_upszone',
	address2_addressid: 'address2_addressid',
	slaname: 'slaname',
	parentaccountidyominame: 'parentaccountidyominame',
	address2_primarycontactname: 'address2_primarycontactname',
	statecode: 'statecode',
}

export enum AccountModelAddress1AddressType {
	BillTo = 1,
	ShipTo = 2,
	Primary = 3,
	Other = 4,
}

export enum AccountModelAddress1ShippingMethod {
	Airborne = 1,
	DHL = 2,
	FedEx = 3,
	UPS = 4,
	PostalMail = 5,
	FullLoad = 6,
	WillCall = 7,
}

export enum AccountModelPaymentTerms {
	Net30 = 1,
	N210Net30 = 2,
	Net45 = 3,
	Net60 = 4,
}

export enum AccountModelCategory {
	PreferredCustomer = 1,
	Standard = 2,
}

export enum AccountModelAddress1FreightTerms {
	FOB = 1,
	NoCharge = 2,
}

export enum AccountModelAccountRating {
	DefaultValue = 1,
}

export enum AccountModelPreferredTime {
	Morning = 1,
	Afternoon = 2,
	Evening = 3,
}

export enum AccountModelClassification {
	DefaultValue = 1,
}

export enum AccountModelRelationshipType {
	Competitor = 1,
	Consultant = 2,
	Customer = 3,
	Investor = 4,
	Partner = 5,
	Influencer = 6,
	Press = 7,
	Prospect = 8,
	Reseller = 9,
	Supplier = 10,
	Vendor = 11,
	Other = 12,
}

export enum AccountModelOwnership {
	Public = 1,
	Private = 2,
	Subsidiary = 3,
	Other = 4,
}

export enum AccountModelPreferredMethodofContact {
	Any = 1,
	Email = 2,
	Phone = 3,
	Fax = 4,
	Mail = 5,
}

export enum AccountModelTerritoryCode {
	DefaultValue = 1,
}

export enum AccountModelIndustry {
	Accounting = 1,
	AgricultureandNonpetrolNaturalResourceExtraction = 2,
	BroadcastingPrintingandPublishing = 3,
	Brokers = 4,
	BuildingSupplyRetail = 5,
	BusinessServices = 6,
	Consulting = 7,
	ConsumerServices = 8,
	DesignDirectionandCreativeManagement = 9,
	DistributorsDispatchersandProcessors = 10,
	DoctorsOfficesandClinics = 11,
	DurableManufacturing = 12,
	EatingandDrinkingPlaces = 13,
	EntertainmentRetail = 14,
	EquipmentRentalandLeasing = 15,
	Financial = 16,
	FoodandTobaccoProcessing = 17,
	InboundCapitalIntensiveProcessing = 18,
	InboundRepairandServices = 19,
	Insurance = 20,
	LegalServices = 21,
	NonDurableMerchandiseRetail = 22,
	OutboundConsumerService = 23,
	PetrochemicalExtractionandDistribution = 24,
	ServiceRetail = 25,
	SIGAffiliations = 26,
	SocialServices = 27,
	SpecialOutboundTradeContractors = 28,
	SpecialtyRealty = 29,
	Transportation = 30,
	UtilityCreationandDistribution = 31,
	VehicleRetail = 32,
	Wholesale = 33,
}

export enum AccountModelBusinessType {
	DefaultValue = 1,
}

export enum AccountModelShippingMethod {
	DefaultValue = 1,
}

export enum AccountModelAddress2AddressType {
	DefaultValue = 1,
}

export enum AccountModelCustomerSize {
	DefaultValue = 1,
}

export enum AccountModelAddress2ShippingMethod {
	DefaultValue = 1,
}

export enum AccountModelPreferredDay {
	Sunday = 0,
	Monday = 1,
	Tuesday = 2,
	Wednesday = 3,
	Thursday = 4,
	Friday = 5,
	Saturday = 6,
}

export enum AccountModelAddress2FreightTerms {
	DefaultValue = 1,
}