import { Entity, EntityPluralNames } from '../constants/Entities';

export const ContactModel = {
	_entityName: Entity.Contact,
	_entityPluralName: EntityPluralNames.Contact,
	_id: Entity.Contact + 'id',

	preferredcontactmethodcodename: 'preferredcontactmethodcodename',
	emailaddress3: 'emailaddress3',
	emailaddress2: 'emailaddress2',
	emailaddress1: 'emailaddress1',
	address3_addresstypecode: 'address3_addresstypecode',
	address1_city: 'address1_city',
	address3_line1: 'address3_line1',
	address1_line1: 'address1_line1',
	educationcodename: 'educationcodename',
	address1_longitude: 'address1_longitude',
	haschildrencodename: 'haschildrencodename',
	address2_freighttermscodename: 'address2_freighttermscodename',
	modifiedon: 'modifiedon',
	aging90: 'aging90',
	overriddencreatedon: 'overriddencreatedon',
	yomilastname: 'yomilastname',
	yomifirstname: 'yomifirstname',
	statuscodename: 'statuscodename',
	donotpostalmail: 'donotpostalmail',
	yomifullname: 'yomifullname',
	createdbyexternalpartyname: 'createdbyexternalpartyname',
	address1_addresstypecode: 'address1_addresstypecode',
	address3_line2: 'address3_line2',
	modifiedbyyominame: 'modifiedbyyominame',
	aging30: 'aging30',
	address1_freighttermscode: 'address1_freighttermscode',
	address3_telephone1: 'address3_telephone1',
	sample_contributorsidname: 'sample_contributorsidname',
	sample_contributorsid: 'sample_contributorsid',
	sample_contributorsidLookup: '_sample_contributorsid_value',
	address3_line3: 'address3_line3',
	donotsendmm: 'donotsendmm',
	createdbyexternalparty: 'createdbyexternalparty',
	createdbyexternalpartyLookup: '_createdbyexternalparty_value',
	creditonhold: 'creditonhold',
	transactioncurrencyidname: 'transactioncurrencyidname',
	donotbulkpostalmail: 'donotbulkpostalmail',
	aging60_base: 'aging60_base',
	preferredsystemuseridyominame: 'preferredsystemuseridyominame',
	address1_shippingmethodcode: 'address1_shippingmethodcode',
	paymenttermscode: 'paymenttermscode',
	gendercode: 'gendercode',
	address3_utcoffset: 'address3_utcoffset',
	externaluseridentifier: 'externaluseridentifier',
	address3_primarycontactname: 'address3_primarycontactname',
	modifiedbyexternalpartyyominame: 'modifiedbyexternalpartyyominame',
	entityimage_url: 'entityimage_url',
	preferredsystemuseridname: 'preferredsystemuseridname',
	owningbusinessunit: 'owningbusinessunit',
	owningbusinessunitLookup: '_owningbusinessunit_value',
	preferredappointmenttimecode: 'preferredappointmenttimecode',
	preferredappointmentdaycodename: 'preferredappointmentdaycodename',
	address2_stateorprovince: 'address2_stateorprovince',
	participatesinworkflowname: 'participatesinworkflowname',
	mobilephone: 'mobilephone',
	parentcustomeridyominame: 'parentcustomeridyominame',
	address2_country: 'address2_country',
	address2_line2: 'address2_line2',
	address3_stateorprovince: 'address3_stateorprovince',
	modifiedonbehalfby: 'modifiedonbehalfby',
	modifiedonbehalfbyLookup: '_modifiedonbehalfby_value',
	slaid: 'slaid',
	slaidLookup: '_slaid_value',
	assistantphone: 'assistantphone',
	address3_shippingmethodcodename: 'address3_shippingmethodcodename',
	parentcontactid: 'parentcontactid',
	parentcontactidLookup: '_parentcontactid_value',
	statuscode: 'statuscode',
	onholdtime: 'onholdtime',
	parentcontactidyominame: 'parentcontactidyominame',
	address3_longitude: 'address3_longitude',
	address3_fax: 'address3_fax',
	creditlimit: 'creditlimit',
	birthdate: 'birthdate',
	address1_utcoffset: 'address1_utcoffset',
	managerphone: 'managerphone',
	employeeid: 'employeeid',
	versionnumber: 'versionnumber',
	donotsendmarketingmaterialname: 'donotsendmarketingmaterialname',
	modifiedbyexternalpartyname: 'modifiedbyexternalpartyname',
	statecodename: 'statecodename',
	address3_upszone: 'address3_upszone',
	telephone1: 'telephone1',
	customertypecode: 'customertypecode',
	donotbulkpostalmailname: 'donotbulkpostalmailname',
	exchangerate: 'exchangerate',
	address2_county: 'address2_county',
	isprivate: 'isprivate',
	telephone3: 'telephone3',
	customersizecode: 'customersizecode',
	preferredcontactmethodcode: 'preferredcontactmethodcode',
	childrensnames: 'childrensnames',
	address1_addresstypecodename: 'address1_addresstypecodename',
	address2_latitude: 'address2_latitude',
	createdon: 'createdon',
	donotbulkemail: 'donotbulkemail',
	slaname: 'slaname',
	marketingonlyname: 'marketingonlyname',
	donotfax: 'donotfax',
	familystatuscodename: 'familystatuscodename',
	annualincome_base: 'annualincome_base',
	aging90_base: 'aging90_base',
	address1_composite: 'address1_composite',
	firstname: 'firstname',
	createdonbehalfby: 'createdonbehalfby',
	createdonbehalfbyLookup: '_createdonbehalfby_value',
	address2_freighttermscode: 'address2_freighttermscode',
	preferredappointmenttimecodename: 'preferredappointmenttimecodename',
	callback: 'callback',
	address2_postalcode: 'address2_postalcode',
	educationcode: 'educationcode',
	lastusedincampaign: 'lastusedincampaign',
	paymenttermscodename: 'paymenttermscodename',
	utcconversiontimezonecode: 'utcconversiontimezonecode',
	processid: 'processid',
	owneridyominame: 'owneridyominame',
	governmentid: 'governmentid',
	isautocreate: 'isautocreate',
	isbackofficecustomername: 'isbackofficecustomername',
	address2_shippingmethodcodename: 'address2_shippingmethodcodename',
	address2_line3: 'address2_line3',
	description: 'description',
	modifiedby: 'modifiedby',
	modifiedbyLookup: '_modifiedby_value',
	entityimage: 'entityimage',
	timezoneruleversionnumber: 'timezoneruleversionnumber',
	spousesname: 'spousesname',
	address1_county: 'address1_county',
	createdbyname: 'createdbyname',
	shippingmethodcodename: 'shippingmethodcodename',
	home2: 'home2',
	donotemail: 'donotemail',
	address3_county: 'address3_county',
	address3_freighttermscodename: 'address3_freighttermscodename',
	donotphonename: 'donotphonename',
	pager: 'pager',
	address2_postofficebox: 'address2_postofficebox',
	address2_telephone1: 'address2_telephone1',
	address2_telephone2: 'address2_telephone2',
	address2_telephone3: 'address2_telephone3',
	aging60: 'aging60',
	address1_addressid: 'address1_addressid',
	traversedpath: 'traversedpath',
	followemailname: 'followemailname',
	annualincome: 'annualincome',
	owninguser: 'owninguser',
	owninguserLookup: '_owninguser_value',
	websiteurl: 'websiteurl',
	address2_name: 'address2_name',
	middlename: 'middlename',
	address3_telephone2: 'address3_telephone2',
	entityimageid: 'entityimageid',
	address3_freighttermscode: 'address3_freighttermscode',
	timespentbymeonemailandmeetings: 'timespentbymeonemailandmeetings',
	parentcustomeridname: 'parentcustomeridname',
	entityimage_timestamp: 'entityimage_timestamp',
	owneridname: 'owneridname',
	creditonholdname: 'creditonholdname',
	address3_shippingmethodcode: 'address3_shippingmethodcode',
	createdonbehalfbyyominame: 'createdonbehalfbyyominame',
	address2_composite: 'address2_composite',
	territorycodename: 'territorycodename',
	address1_country: 'address1_country',
	customertypecodename: 'customertypecodename',
	owningteam: 'owningteam',
	owningteamLookup: '_owningteam_value',
	address1_stateorprovince: 'address1_stateorprovince',
	address3_addresstypecodename: 'address3_addresstypecodename',
	isprivatename: 'isprivatename',
	marketingonly: 'marketingonly',
	modifiedonbehalfbyname: 'modifiedonbehalfbyname',
	createdonbehalfbyname: 'createdonbehalfbyname',
	address1_line3: 'address1_line3',
	createdbyexternalpartyyominame: 'createdbyexternalpartyyominame',
	address1_freighttermscodename: 'address1_freighttermscodename',
	slainvokedid: 'slainvokedid',
	slainvokedidLookup: '_slainvokedid_value',
	mastercontactidname: 'mastercontactidname',
	jobtitle: 'jobtitle',
	nickname: 'nickname',
	transactioncurrencyid: 'transactioncurrencyid',
	transactioncurrencyidLookup: '_transactioncurrencyid_value',
	managername: 'managername',
	address1_telephone1: 'address1_telephone1',
	address1_telephone2: 'address1_telephone2',
	address1_telephone3: 'address1_telephone3',
	isbackofficecustomer: 'isbackofficecustomer',
	contactid: 'contactid',
	suffix: 'suffix',
	donotemailname: 'donotemailname',
	slainvokedidname: 'slainvokedidname',
	fax: 'fax',
	masterid: 'masterid',
	masteridLookup: '_masterid_value',
	mastercontactidyominame: 'mastercontactidyominame',
	assistantname: 'assistantname',
	yomimiddlename: 'yomimiddlename',
	ownerid: 'ownerid',
	address3_country: 'address3_country',
	address2_utcoffset: 'address2_utcoffset',
	participatesinworkflow: 'participatesinworkflow',
	creditlimit_base: 'creditlimit_base',
	address2_fax: 'address2_fax',
	merged: 'merged',
	owneridtype: 'owneridtype',
	address2_longitude: 'address2_longitude',
	modifiedbyexternalparty: 'modifiedbyexternalparty',
	modifiedbyexternalpartyLookup: '_modifiedbyexternalparty_value',
	accountrolecode: 'accountrolecode',
	donotpostalmailname: 'donotpostalmailname',
	accountid: 'accountid',
	accountidLookup: '_accountid_value',
	address3_latitude: 'address3_latitude',
	donotphone: 'donotphone',
	address1_shippingmethodcodename: 'address1_shippingmethodcodename',
	accountidname: 'accountidname',
	address1_primarycontactname: 'address1_primarycontactname',
	statecode: 'statecode',
	lastonholdtime: 'lastonholdtime',
	address1_line2: 'address1_line2',
	modifiedonbehalfbyyominame: 'modifiedonbehalfbyyominame',
	createdby: 'createdby',
	createdbyLookup: '_createdby_value',
	parentcustomerid: 'parentcustomerid',
	address2_addresstypecode: 'address2_addresstypecode',
	address2_upszone: 'address2_upszone',
	followemail: 'followemail',
	accountrolecodename: 'accountrolecodename',
	address3_name: 'address3_name',
	donotfaxname: 'donotfaxname',
	gendercodename: 'gendercodename',
	address3_composite: 'address3_composite',
	address2_addresstypecodename: 'address2_addresstypecodename',
	salutation: 'salutation',
	leadsourcecodename: 'leadsourcecodename',
	address1_postalcode: 'address1_postalcode',
	company: 'company',
	stageid: 'stageid',
	address3_telephone3: 'address3_telephone3',
	address3_postalcode: 'address3_postalcode',
	donotbulkemailname: 'donotbulkemailname',
	preferredappointmentdaycode: 'preferredappointmentdaycode',
	customersizecodename: 'customersizecodename',
	address2_addressid: 'address2_addressid',
	anniversary: 'anniversary',
	importsequencenumber: 'importsequencenumber',
	address2_city: 'address2_city',
	haschildrencode: 'haschildrencode',
	telephone2: 'telephone2',
	mergedname: 'mergedname',
	subscriptionid: 'subscriptionid',
	familystatuscode: 'familystatuscode',
	department: 'department',
	address3_city: 'address3_city',
	business2: 'business2',
	preferredsystemuserid: 'preferredsystemuserid',
	preferredsystemuseridLookup: '_preferredsystemuserid_value',
	aging30_base: 'aging30_base',
	address1_name: 'address1_name',
	address1_fax: 'address1_fax',
	address1_latitude: 'address1_latitude',
	address2_shippingmethodcode: 'address2_shippingmethodcode',
	address3_postofficebox: 'address3_postofficebox',
	parentcustomeridtype: 'parentcustomeridtype',
	parentcontactidname: 'parentcontactidname',
	modifiedbyname: 'modifiedbyname',
	createdbyyominame: 'createdbyyominame',
	leadsourcecode: 'leadsourcecode',
	address2_line1: 'address2_line1',
	address1_upszone: 'address1_upszone',
	lastname: 'lastname',
	accountidyominame: 'accountidyominame',
	shippingmethodcode: 'shippingmethodcode',
	territorycode: 'territorycode',
	ftpsiteurl: 'ftpsiteurl',
	numberofchildren: 'numberofchildren',
	address1_postofficebox: 'address1_postofficebox',
	address2_primarycontactname: 'address2_primarycontactname',
	fullname: 'fullname',
	address3_addressid: 'address3_addressid',
}

export enum ContactModelAddress3AddressType {
	DefaultValue = 1,
}

export enum ContactModelAddress1AddressType {
	BillTo = 1,
	ShipTo = 2,
	Primary = 3,
	Other = 4,
}

export enum ContactModelAddress1FreightTerms {
	FOB = 1,
	NoCharge = 2,
}

export enum ContactModelAddress1ShippingMethod {
	Airborne = 1,
	DHL = 2,
	FedEx = 3,
	UPS = 4,
	PostalMail = 5,
	FullLoad = 6,
	WillCall = 7,
}

export enum ContactModelPaymentTerms {
	Net30 = 1,
	N210Net30 = 2,
	Net45 = 3,
	Net60 = 4,
}

export enum ContactModelGender {
	Male = 1,
	Female = 2,
}

export enum ContactModelPreferredTime {
	Morning = 1,
	Afternoon = 2,
	Evening = 3,
}

export enum ContactModelRelationshipType {
	DefaultValue = 1,
}

export enum ContactModelCustomerSize {
	DefaultValue = 1,
}

export enum ContactModelPreferredMethodofContact {
	Any = 1,
	Email = 2,
	Phone = 3,
	Fax = 4,
	Mail = 5,
}

export enum ContactModelAddress2FreightTerms {
	DefaultValue = 1,
}

export enum ContactModelEducation {
	DefaultValue = 1,
}

export enum ContactModelAddress3FreightTerms {
	DefaultValue = 1,
}

export enum ContactModelAddress3ShippingMethod {
	DefaultValue = 1,
}

export enum ContactModelRole {
	DecisionMaker = 1,
	Employee = 2,
	Influencer = 3,
}

export enum ContactModelAddress2AddressType {
	DefaultValue = 1,
}

export enum ContactModelPreferredDay {
	Sunday = 0,
	Monday = 1,
	Tuesday = 2,
	Wednesday = 3,
	Thursday = 4,
	Friday = 5,
	Saturday = 6,
}

export enum ContactModelHasChildren {
	DefaultValue = 1,
}

export enum ContactModelMaritalStatus {
	Single = 1,
	Married = 2,
	Divorced = 3,
	Widowed = 4,
}

export enum ContactModelAddress2ShippingMethod {
	DefaultValue = 1,
}

export enum ContactModelLeadSource {
	DefaultValue = 1,
}

export enum ContactModelShippingMethod {
	DefaultValue = 1,
}

export enum ContactModelTerritory {
	DefaultValue = 1,
}